### ISSUE TITLE
请问，对您的源码我们能做什么和不能做什么？

### ISSUE THREAD

**Issue by cupen** [uustory/U8Server#5]
打扰啦，暂未看到您发表公共授权协议，有点不敢轻举妄动。
也许您脑海里有个类似 MIT, LGPL 或者 BSD 授权协议正打算公布呢？

**Comment by u8-xiaohei** [comment]
抱歉，之前没有加授权文件。 现在已经加上了，目前基于Apache License, Version 2.0授权协议。
企业可以对代码进行定制和修改，以及进行商用。只需要保证U8Server的著作权归属和版权申明即可。

**Comment by cupen** [comment]
收到，非常感谢。
