### ISSUE TITLE
请支持游戏分区的情况

### ISSUE THREAD

**Issue by huan9huan** [uustory/U8Server#6]
支付回调（从u8server到game server调用）的时候，游戏服是多个服，而不是一个，这个怎么处理？目前u8server只支持单服。
或者有一些建议吗？

**Comment by u8-xiaohei** [comment]
之前的想法是，游戏服务器那边的架构会是这样：一个中心服务器＋N组游戏服务器。 登陆认证和支付回调都会经过中心服务器做中转。

**Comment by huan9huan** [comment]
好，目前已经采用第一种方案，谢谢关注和回答

**Comment by cupen** [comment]
@u8-xiaohei 哈哈，说到应用宝，在下有一肚子槽要吐。这货真特喵奇葩啊，支付分为`道具购买`和`余额托管`。前者是几乎所有移动渠道都支持的，但他只给网页游戏使用，后者怎么看都是设计给单机用的。sdk包里的文档也是混乱不堪，我用脚趾头写的都比他条理清晰，好在他们平台中心网站上的在线文档质量还不错。
