### ISSUE TITLE
struts 2 漏洞

### ISSUE THREAD

**Issue by huan9huan** [uustory/U8Server#8]
目前pom xml中使用的struts版本被爆出漏洞：https://www.oschina.net/news/72870/apache-struts-2

要升级到2.3.25以上

**Comment by masonzhang** [comment]
报告一个真实案例，我们的U8服务器的webapps目录下U8的包位置下面出现了一个lndex.jsp的文件，记得第一个字母是小写的"L"。然后有段木马注入。删除该文件无法解决问题。木马作者已经通过这个木马给自己留了后门。5月2日这个后门被启动了，持续了24小时，一个名为112266的进程在tomcat的用户下面启动，持续向外发送数据，占用了服务器的全部带宽（20M），CPU利用率持续75%。

希望引起重视。

**Comment by u8-xiaohei** [comment]
@huan9huan 
@masonzhang 

谢谢提醒，已经修复了，屏蔽了struts动态代码调用
